### PR TITLE
Add pyproject.toml and support Cython 3

### PR DESCRIPTION
**Pull request by dalcinl**

### CODE REVIEW

**Comment by benlandrum** [comment]
Looks like you have the rest of this. Is the MacOS ARM issue new? I don't remember seeing that one previously.

**Comment by dalcinl** [comment]
> Looks like you have the rest of this

I still have to fix Azure Pipelines. I'll take a look tomorrow morning. I'm not sure whether to keep insisting with conda-forge environments, of just use the same approach as here, but for the older Python versions (like I do in mpi4py).

> Is the MacOS ARM issue new?

The ARM macOS images do not have the older versions of Python. Other than that, there are no issues. What do you meant exactly?

**Comment by benlandrum** [comment]
> The ARM macOS images do not have the older versions of Python. Other than that, there are no issues. What do you meant exactly?

Yes, that's the issue. I had for instance `macos-latest` and Python 3.7 working a few weeks ago with my draft, when `macos-latest` was 12.7.4 (see [here](https://github.com/benlandrum/mpi4py-fft/actions/runs/8593783577/job/23545806619)). Now on 14.4.1 I get `The version '3.7' with architecture 'arm64' was not found for macOS 14.4.1.`

**Comment by dalcinl** [comment]
For the time being, testing of all he IO stuff will not run and it uncovered.
The build fixes and Cython 3 updates are more important that 100% test coverage.

**Pull request merged**
